captainVersion: 4
services:
    # Directus
    $$cap_appname:
        image: directus/directus
        restart: always
        environment:
            KEY: $$cap_directus_auth_public_key
            SECRET: $$cap_directus_auth_secret_key
            DB_CLIENT: 'pg'
            DB_CONNECTION_STRING: $$cap_db_connection_string
            NODE_TLS_REJECT_UNAUTHORIZED: 0
            CACHE_ENABLED: 'true'
            ADMIN_EMAIL: admin@synco.re
            ADMIN_PASSWORD: $$cap_admin_password
            PUBLIC_URL: $$cap_public_url
            STORAGE_LOCATIONS: s3
            STORAGE_S3_DRIVER: s3
            STORAGE_S3_KEY: $$cap_s3_key
            STORAGE_LOCAL_SECRET: $$cap_s3_secret
            STORAGE_LOCAL_BUCKET: syncore-cdn
            STORAGE_LOCAL_REGION: nyc3
            STORAGE_LOCAL_ENDPOINT: nyc3.digitaloceanspaces.com
            STORAGE_LOCAL_ACL: public-read
            STORAGE_LOCAL_ROOT: $$cap_s3_root
            EMAIL_TRANSPORT: mailgun
            EMAIL_FROM: $$cap_email_from
            EMAIL_MAILGUN_API_KEY: $$cap_email_key
            EMAIL_MAILGUN_DOMAIN: $$cap_email_domain
            CORS_ENABLED: true
            CORS_ORIGIN: true
        caproverExtra:
            containerHttpPort: '8055'
caproverOneClickApp:
    variables:
        - description: Database connection string URL, you should be using the VPC connection string for extra security.
          id: $$cap_db_connection_string
          label: Connection String
          validRegex: /postgresql:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/

        - description: Directus Auth Secret Key (must not be the same as Directus Auth Public Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_secret_key
          label: Directus Auth Secret Key
          validRegex: /^(?=.*\d).{10,}$/

        - description: Directus Auth Public Key (must not be the same as Directus Auth Secret Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_public_key
          label: Directus Auth Public Key
          validRegex: /^(?=.*\d).{10,}$/

        - description: Directus admin user password
          defaultValue: projNameinit01!
          id: $$cap_admin_password
          label: Directus admin user password

        - description: S3 API key
          id: $$cap_s3_key
          label: S3 API key

        - description: S3 API secret
          id: $$cap_s3_secret
          label: S3 API secret

        - description: The folder name where assets are uploaded to on S3. This should be the name of the client.
          id: $$cap_s3_root
          label: S3 Root

        - description: The address emails will be sent from.
          defaultValue: 'no-reply@synco.re'
          id: $$cap_email_from
          label: Email from

        - description: The domain Mailgun will use to send emails.
          id: $$cap_email_domain
          label: Mailgun domain
    instructions:
        end: 'Directus has been deployed: http://$$cap_appname.$$cap_root_domain'
        start: >-
            Syncore's customized Directus app.
    displayName: 'Syncore — Directus'
    isOfficial: false
    description: Syncore's customized Directus app.
